version: '3'
services:
  vprodb:
    image: mechai/vprofiledb:latest
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass


  vprocache01:
    image: memcached:latest
    ports:
      - "1121:1121"

  vprormq01:
    image: rabbitmq:latest
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    image: mechai/vprofileapp:V1
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    image: nginx:latest
    ports:
      - "80:80"
          

volumes:
  vproappdata: {}        
  vprodbdata: {}



